### ISSUE TITLE
NVIDIA GeForce RTX 5080 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.

### ISSUE THREAD

**Issue by dw5304** [erew123/alltalk_tts#636]
Fresh install windows with NVidia GeForce rtx508 any suggestions on how to fix, 

[AllTalk TTS] xtts model downloaded and configuration updated successfully.
[AllTalk TTS]
[AllTalk TTS] If you have you have UPGRADED from v1 ensure you have re-installed
[AllTalk TTS] the requirements. Otherwise you will get failures and errors!
[AllTalk TTS] On Linux ignore the 'sparse_attn requires a torch version' and
[AllTalk TTS] 'using untested triton version' messages.
[AllTalk TTS]
[AllTalk TTS] WAV file deletion : Disabled
[AllTalk TTS] Github updated    : 15th July 2025 at 05:10 Branch: alltalkbeta
[AllTalk ENG] Transcoding       : ffmpeg found
D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\torch\cuda\__init__.py:54: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
[AllTalk ENG] DeepSpeed version : 0.14.0+ce78a63
[AllTalk ENG] Python Version    : 3.11.9
[AllTalk ENG] PyTorch Version   : 2.2.1
[AllTalk ENG] CUDA Version      : 12.1
[AllTalk ENG]
[AllTalk ENG] Loading XTTS model xttsv2_2.0.3 on cuda
D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\torch\cuda\__init__.py:218: UserWarning:
NVIDIA GeForce RTX 5080 Laptop GPU with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
[AllTalk ENG] Model License : https://coqui.ai/cpml.txt
[AllTalk ENG] Model Loadtime: 6.77 seconds
[AllTalk TTS]
[AllTalk TTS] API Address : 127.0.0.1:7851
[AllTalk TTS] Gradio Light: http://127.0.0.1:7852
[AllTalk TTS] Gradio Dark : http://127.0.0.1:7852?__theme=dark
[AllTalk TTS]
[AllTalk TTS] AllTalk WIKI: https://github.com/erew123/alltalk_tts/wiki
[AllTalk TTS] Errors Help : https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List
[AllTalk TTS]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio\route_utils.py", line 761, in __call__
    await self.app(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\fastapi\routing.py", line 297, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio\routes.py", line 431, in main
    gradio_api_info = api_info(False)
                      ^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio\routes.py", line 460, in api_info
    app.api_info = app.get_blocks().get_api_info()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio\blocks.py", line 2852, in get_api_info
    python_type = client_utils.json_schema_to_python_type(info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio_client\utils.py", line 893, in json_schema_to_python_type
    type_ = _json_schema_to_python_type(schema, schema.get("$defs"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio_client\utils.py", line 947, in _json_schema_to_python_type
    des = [
          ^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio_client\utils.py", line 948, in <listcomp>
    f"{n}: {_json_schema_to_python_type(v, defs)}{get_desc(v)}"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio_client\utils.py", line 955, in _json_schema_to_python_type
    f"str, {_json_schema_to_python_type(schema['additionalProperties'], defs)}"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio_client\utils.py", line 901, in _json_schema_to_python_type
    type_ = get_type(schema)
            ^^^^^^^^^^^^^^^^
  File "D:\alltalk_tts\alltalk_environment\env\Lib\site-packages\gradio_client\utils.py", line 863, in get_type
    if "const" in schema:
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'bool' is not iterable

**Comment by SameSport** [comment]
I have the same problem on Nvidia RTX 5070Ti

**Comment by Nicholas-Stephens** [comment]
I had a error like that with a RTX 6000 pro and I was able to get it working by using 

pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu128

and in the finetune.py code i changed line 552 to pytorch_cuda_status = cuda_version.startswith("11.") or cuda_version.startswith("12.") 

And line 1216 to with torch.amp.autocast('cuda'): 

hope this can at least point you in the correct direction

**Comment by fridolie** [comment]
Nicholas have right but deepspeed dont work and need install 0.17.5+e1560d84 deepspeed veriosn. I made this install normal standalone version with bat. Then get to env 

pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu128

Then work this version but without deepspeed.

I used version 1 of pinokio alltalk. After installing and changing pip, I copied the deespeed folder and deepspeed-0.17.5+e1560d84.dist-info from pinokio and pasted them into alltalk_tts\alltalk_environment\env\Lib\site-packages . After that, it detects deepspeed normally. Sorry i dont know which command install this version deepspeed. 
I know very little about coding, I'm still learning and AI helps a bit.
Maybe someone can help and find the code to install this version of deepspeed with the command

Many thanks to Nicholas-Stephens

I have RTX 5070

<img width="961" height="577" alt="Image" src="https://github.com/user-attachments/assets/4e1a30bf-c185-4f3d-9d56-8ea89061e5d8" />

**Comment by perkel666** [comment]
I have RTX5090 (WINDOWS) and thanks to guys above I was able to figure it out:

1. Install AllTalkV2 via this way in folder you want:

`git clone -b alltalkbeta https://github.com/erew123/alltalk_tts`

2. Run atsetup.bat and install it as **standalone**

3. Once it finishes installing everything then run start_alltalk.bat and choose XTTS (3) option and let it download run it at least once.

4. Open Command Prompt (search for "cmd" in Windows Start menu, or run cmd.exe in administrator mode). Navigate to the env folder: (I have it in D:\AI\alltalk_tts)

`cd /D D:\AI\alltalk_tts\alltalk_environment\env`

5. Activate now environment:

`call "D:\AI\alltalk_tts\alltalk_environment\conda\condabin\conda.bat" activate "D:\AI\alltalk_tts\alltalk_environment\env"`

6. Unistall old pytorch:

`pip uninstall torch torchvision torchaudio `

7. Install proper torch and correct code:

`pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cu128`

in the finetune.py code change line 552: to 
`pytorch_cuda_status = cuda_version.startswith("11.") or cuda_version.startswith("12.")`

Same finetune.py change line 1216 to:
'torch.amp.autocast('cuda'):'

8. Now uninstall deepspeed:

`pip uninstall deepspeed -y`

9. And install specific working version:

`pip install https://github.com/6Morpheus6/deepspeed-windows-wheels/releases/download/v0.17.5/deepspeed-0.17.5+e1560d84-2.7torch+cu128-cp311-cp311-win_amd64.whl`

Congratz you now have working all talk V2 with RTX5000 series gpu.
